PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix envo: <http://purl.obolibrary.org/obo/ENVO_>
construct {
?s rdfs:subClassOf <http://example.org/nmsfe/env_medium_proposed> .
[ rdf:type owl:Axiom ;
owl:annotatedSource ?s;
owl:annotatedProperty rdfs:subClassOf ;
owl:annotatedTarget <http://example.org/nmsfe/env_medium_proposed> ;
rdfs:seeAlso <http://example.org/nmsfe/subclass-of-env-material-query> ;
] .
}
WHERE
{
    SERVICE <https://ubergraph.apps.renci.org/sparql> {  ?s  rdfs:isDefinedBy  <http://purl.obolibrary.org/obo/envo.owl> ;
    rdfs:subClassOf   <http://purl.obolibrary.org/obo/ENVO_00010483> .}
}
